# Étape de construction
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Étape de production
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

# Exposez le port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]