version: '3.8'
 
services:
  coordination-service:
    build: ./services/care-coordination-service
    ports:
      - "5001:5001"
 
  alert-service:
    build: ./services/complication-alert-service
    ports:
      - "5002:5002"
 
  exercise-service:
    build: ./services/exercise-guidance-service
    ports:
      - "5003:5003"
 
  questionnaire-service:
    build: ./services/questionnaire-service
    ports:
      - "5004:5004"
 
  recovery-plan-service:
    build: ./services/recovery-plan-service
    ports:
      - "5005:5005"
 
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # NGINX écoute sur le port 80